### ISSUE TITLE
Kalan Crudlar Yapılacak.

### ISSUE THREAD

**Issue by nil1lik** [nil1lik/TobetoPlatformCleanArchitecture#5]
Announcement, ProfileApplication, ApplicationStep, AsyncLesson, Calendar, Certificate, City, Company, Contact, Country, Course, CourseClass YAPILDI.
Bunlar dışındaki entitylerin crudları yapılacak.

**Comment by nidakul** [comment]
ApplicationStep, District, EducationAboutCategory, EducationAbout, EducationAdmiration, EducationPath, ExamResult, Exam, Experience, Graduation, Instructor, LanguageLevel, Language, LessonType, ProfileApplicationStep, Skill, SocialMediaAccount, SocialMediaCategory, Survey, SyncLesson, UserApplication, VideoCategory, VideoDetailSubcategory, VideoLanguage CRUDLARI YAPILDI.
